// Builds supabase/seed.sql from content/seed-data.json.
// Usage: npm run seed:sql
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const data = JSON.parse(readFileSync(join(root, "content/seed-data.json"), "utf8"));

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const ts = (daysAgo) => `now() - interval '${daysAgo} days' - interval '${(daysAgo * 37) % 600} minutes'`;

const lines = [
  "-- Sample data: 12 prayer requests and 5 answered prayers.",
  "-- Generated by scripts/generate-seed.mjs from content/seed-data.json. Do not edit by hand.",
  "-- Run AFTER schema.sql. Safe to run twice (existing rows are skipped).",
  "",
  "insert into public.prayers (id, name, request, category, is_public, status, prayed_count, created_at, approved_at) values",
  data.prayers
    .map(
      (p) =>
        `  (${q(p.id)}, ${q(p.name)}, ${q(p.request)}, ${q(p.category)}, ${p.isPublic}, ${q(p.status)}, ${p.prayedCount}, ${ts(p.daysAgo)}, ${p.status === "approved" ? ts(p.daysAgo) : "null"})`,
    )
    .join(",\n") + "\non conflict (id) do nothing;",
  "",
  "insert into public.testimonies (id, name, prayed_for, answer, prayer_id, status, praise_count, created_at, approved_at) values",
  data.testimonies
    .map(
      (t) =>
        `  (${q(t.id)}, ${q(t.name)}, ${q(t.prayedFor)}, ${q(t.answer)}, ${q(t.prayerId)}, ${q(t.status)}, ${t.praiseCount}, ${ts(t.daysAgo)}, ${t.status === "approved" ? ts(t.daysAgo) : "null"})`,
    )
    .join(",\n") + "\non conflict (id) do nothing;",
  "",
];

writeFileSync(join(root, "supabase/seed.sql"), lines.join("\n"));
console.log(`Wrote supabase/seed.sql (${data.prayers.length} prayers, ${data.testimonies.length} testimonies)`);
